set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set autoindent

if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  "setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

let g:pandoc#syntax#conceal#blacklist = ["atx"]
let g:pandoc#folding#fdc = 0
let g:pandoc#folding#level = 5
let g:pandoc#spell#enabled = 0

" Enable Racket Support
if has("autocmd")
    syntax off
endif

execute pathogen#infect()
