set nocompatible
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set incsearch

if has("multi_byte")
  if &termencoding == ""
    let &termencoding = &encoding
  endif
  set encoding=utf-8
  setglobal fileencoding=utf-8
  setglobal bomb
  set fileencodings=ucs-bom,utf-8,latin1
endif

" Set tabs to be four spaces.
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent

let g:pandoc#syntax#conceal#blacklist = ["atx"]
let g:pandoc#folding#fdc = 0
let g:pandoc#folding#level = 5
let g:pandoc#spell#enabled = 0

" Enable Racket Support
if has("autocmd")
    syntax off
endif


" Javascript symbol manipulation
let g:javascript_conceal_function   = "λ"
let g:javascript_conceal_null       = "ø"
let g:javascript_conceal_this       = "@"
let g:javascript_conceal_return     = "→"
let g:javascript_conceal_static     = "•"
let g:javascript_conceal_super      = "Ω"


execute pathogen#infect()
